#!/usr/bin/env python3
"""Build the public systemic consulting guide. All source content is public copy.
Run from the repository root. Private meeting and registration data never belong here.
"""
from pathlib import Path
from html import escape as e
import json, re

ROOT = Path('flawfulconsulting')
BASE = '/flawfulconsulting/'
PAGES = []
def page(slug, title, deck, sections):
    PAGES.append(dict(slug=slug,title=title,deck=deck,sections=sections))
def s(id, title, body): return dict(id=id,title=title,body=body)
def p(t): return '<p>'+t+'</p>'
def ul(*items): return '<ul>'+''.join('<li>'+x+'</li>' for x in items)+'</ul>'
def q(t): return '<blockquote><p>'+t+'</p></blockquote>'
def table(head, rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def a(slug, text, anchor=''): return f'<a href="{BASE}{slug}/'+('#'+anchor if anchor else '')+'">'+text+'</a>'

page('', 'Systemic consulting', 'Helping people do work they can own. A practical guide to contracting, inquiry, power, learning, and useful intervention.', [
s('start','Start with the work in front of you',p('Consulting begins when someone asks for help. There is a task, a relationship, and a wider situation. How we enter that situation affects what becomes possible. We bring experience and methods; the people we work with bring knowledge, authority, interests, and consequences that we cannot take over.')+p('This guide brings together my consulting teaching and practice from 2022 to 2026, including the slide-free session on 30 September 2026. It draws particularly on Peter Block’s <cite>Flawless Consulting</cite>, with systems thinking, Barry Oshry’s work on systemic position, and practical work on inquiry and intervention. ‘Flawful consulting’ is a reminder that we bring ourselves, our limits, and our fallibility into the work. The subject here remains systemic consulting.')+p('Use it before a difficult conversation, when scoping an assignment, or to reflect on a piece of work. The chapters develop the ideas; the situations and worksheets help you try them. This is an evolving synthesis of the source material at key-concept level, rather than an archive of every slide.')),
s('routes','Choose a way in', '<div class="route-grid">'+''.join('<a class="route" href="'+BASE+slug+'/"><span>'+label+'</span><strong>'+title+'</strong><small>'+desc+'</small></a>' for slug,label,title,desc in [
('roles','01 · Your position','What kind of help am I offering?','Expertise, collaboration, service, and responsibility.'),
('contracting','02 · The agreement','What are we really agreeing?','Purpose, access, authority, internal clients, and recontracting.'),
('inquiry','03 · Understanding','What do we need to find out together?','Evidence, boundaries, discovery, and feedback.'),
('conversations','04 · The relationship','What needs to be said?','Authenticity, concerns, power, and difficult conversations.'),
('intervention','05 · Doing the work','How will this become useful action?','Participation, process, implementation, and endings.'),
('learning','06 · Learning','Can learning be a deliverable?','A worked contract, evidence, and review decisions.'),
('situations','07 · Rehearsal','Try it on a real situation','Eight cases and practical exercises.'),
('related-practice','08 · Connections','How does this connect to other practice?','Facilitation, workshop design, four dynamics, and five core practices.'),
('september-session','09 · The conversation','What did we discuss on 30 September?','A full thematic account and the questions left open.'),
('resources','10 · The sources','Read, watch, listen, and download','The session links, earlier teaching, and annotated resources.')])+'</div>'),
s('picture','The work, in one picture',p('The relationship runs through the whole assignment. Move between these activities as the situation changes; a new piece of evidence may take you straight back to contracting.')+'<figure><a href="downloads/2026-10-01 RedQuadrant systemic consulting practice map v0.01 BT.png"><img src="practice-map.svg" width="1200" height="1120" alt="Systemic consulting practice map: agree the work, inquire together, make sense, act and learn, and review or end. At the centre are shared responsibility, honest conversation, and client ownership. Power, purpose, boundaries, and consequences surround every activity."></a><figcaption>Benjamin P Taylor · systemic consulting · <a href="downloads/2026-10-01 RedQuadrant systemic consulting practice map v0.01 BT.pdf">Download the one-page PDF</a></figcaption></figure>'),
s('use','Three ways to use this guide',ul('<strong>Five minutes before a meeting:</strong> read '+a('contracting','the contracting questions')+' and write down what you need from the client.','<strong>Half an hour with a colleague:</strong> choose one '+a('situations','practice situation')+', rehearse a conversation, and replay the difficult moment.','<strong>A whole assignment:</strong> work through roles, contracting, inquiry, conversations, and intervention. Use '+a('learning','the learning contract')+' to keep evidence connected to decisions.')+p('If you were at the September session, the '+a('september-session','session account')+' will help you reconnect the discussion. If you were not, start with roles: the guide assumes no attendance or prior knowledge.')),
s('search','Find a concept', '<label for="guide-search">Search across the guide</label><input type="search" id="guide-search" placeholder="Try: internal, resistance, learning, boundaries" autocomplete="off"><p id="search-status" role="status" aria-live="polite">Search chapter text, headings, and resources.</p><div id="search-results"></div><noscript><p>Use the chapter links above or your browser’s Find command.</p></noscript>')
])

page('roles','Offering help without taking over','Expertise matters. So do the client’s knowledge, freedom, and responsibility.',[
s('help','Consulting is a relationship',p('A consultant seeks to influence a situation without having direct control over all the action. This includes internal advisers, organisational development practitioners, business partners, specialists, coaches, and external consultants. A job title does not settle the relationship. An external consultant may become a manager; an internal specialist may be consulting in one conversation and exercising delegated authority in the next.')+p('Be clear about the role you are taking. If you accept responsibility for running something, contract for the authority and accountability that go with it. If you are advising, do not quietly take over the client’s decisions. Staying to help implement can be valuable; obscuring who owns the consequences is the problem.')),
s('positions','Three familiar positions, and a fourth temptation',table(['Position','What it can offer','What to watch'],[
('Expert: ‘I can tell you’','Specialist knowledge, judgement, or a technical answer.','The client may surrender contextual knowledge and ownership; the expert may answer the wrong question.'),
('Pair of hands: ‘Tell me what to do’','Reliable delivery of a genuinely defined task.','The brief may go unexamined; useful challenge and professional judgement may disappear.'),
('Collaborator: ‘Let us work on this together’','A relationship in which both contribute knowledge, choices, and responsibility.','Collaboration needs explicit work, time, and authority; the label alone changes nothing.'),
('The quiet fourth position','Working indirectly when a direct challenge would close down useful work.','An unspoken alternative agenda can become manipulation. Ask whether the client could knowingly agree to your approach.')])+p('The September exercise surfaced the attraction of this fourth position. Sometimes timing and tact make a difference. Keep testing your purpose, your accountability, and whether the client can make a meaningful choice. Collaboration can include a direct expert recommendation; it does not require pretending to know nothing.')),
s('service','The space of service',p('Oshry’s account of systemic position helps explain a recurrent pressure. The client has a need and knowledge of their context. The consultant has something to offer, but may feel exposed: will I be accepted, useful, or paid? Anxiety can drive us to demonstrate expertise immediately, or to agree to whatever is asked. Either move can narrow the relationship before we understand the work.')+p('Notice the pressure without treating it as a personal defect. Slow down enough to ask, listen, and state your own requirements. The client’s uncertainty and your uncertainty can become material for joint inquiry. They do not have to be concealed beneath confidence.')+q('‘Before I suggest an approach, I need to understand what you are trying to change, what you have already tried, and what you need from me.’')),
s('responsibility','Shared responsibility',p('Block’s 50/50 formulation is a practical challenge to over-responsibility: both parties contribute to the relationship and the work. The September conversation also used 100/100 to express wholehearted participation. Neither phrase divides tasks, authority, or legal liability into equal shares. Specify the actual responsibilities.')+ul('The consultant owns the quality of their contribution, their methods, honesty about limits, and the commitments they make.','The client owns decisions and actions within their authority, access, participation, and the consequences they retain.','Both own the work of making the relationship usable: surfacing concerns, checking understanding, and renegotiating when necessary.')+p('Do not use shared responsibility to blame someone who has little power. Ask what each person can actually influence, what constraints they face, and who else must join the agreement.')),
s('values','Assumptions and values become practical choices',p('The earlier Flawless material stresses valid information, free and informed choice, and commitment grounded in people’s own interests. Valid information includes what can be observed and what people experience; keep the distinction clear. A feeling is information about experience, not proof of another person’s intention.')+p('State what your practice asks of people. If you value participation but only meet the sponsor, or value learning but reward agreement, your method contradicts your claim. Useful consulting makes those contradictions discussable.')),
s('self','The consultant is in the situation',p('Your presence changes what people say and do. Your confidence, status, identity, commercial interests, favourite methods, and need to help all affect what you notice. Systems thinking does not give you a view from nowhere. It offers ways to make your framing explicit and to test it with others.')+ul('What am I treating as the problem, and what have I left outside?','What answer would make me feel competent or commercially secure?','What would I find hard to hear?','Who experiences the consequences of this work but is absent from the conversation?','What support or supervision do I need to stay useful?'))
])

page('contracting','Contracting for useful work','A contract is an explicit working agreement that you keep revisiting.',[
s('agreement','Contract the task and the relationship',p('A proposal describes a piece of work. Contracting establishes what the parties actually agree to contribute, expect, and decide. Fees, outputs, dates, and scope matter. So do access, candour, participation, confidentiality, and what happens when the work reveals something inconvenient.')+p('Contracting happens throughout the assignment. A new sponsor, blocked access, a changed purpose, or a repeated difficulty can require a new conversation. A signed document does not remove that need.')),
s('questions','Questions worth settling',table(['Area','Questions'],[
('Purpose','What are we trying to make possible, for whom? What decision or action should this work inform?'),
('The work','What are the outputs? What outcomes do we hope for? What do we need to learn? What is outside scope?'),
('Contribution','What do you want from me? What can I offer? What do I need from you? What can you genuinely commit?'),
('Access and participation','Who and what must we be able to reach? Whose experience is missing? Who will make time?'),
('Authority','Who sponsors, pays, decides, implements, and can veto? What can we change here?'),
('Boundaries','What is confidential, with whom, and subject to what exceptions? What may be shared, attributed, recorded, or published?'),
('Working conditions','What are the time, resource, fee, and availability limits? How will we handle disagreement?'),
('Review and ending','When do we review? What could trigger a change of scope, escalation, pause, extension, or ending?')])+p('A useful question from September: ‘If we both agree this is the right thing to do, who can still say no?’ It reveals authority that the immediate relationship may conceal.')),
s('wants','Make wants and offers explicit',p('A consultant may ask for regular sponsor time, access to people doing the work, permission to report unwelcome findings, or a joint decision meeting. These are working requirements. State why they matter and distinguish what is essential from what is negotiable.')+q('‘I can produce the review in this time. To make it useful, I need access to the people handling these cases and a decision meeting with you. If that access is unavailable, we need to narrow the claim the review can make.’')+p('Listen equally carefully to the client’s requirements. They may need a defined report, a deadline, confidentiality, or help navigating a difficult internal position. A report is a perfectly legitimate output when its use is clear. Difficulty starts when everyone behaves as though producing it guarantees change.')),
s('internal','Internal consulting: the triangle and the rectangle',p('An internal consultant belongs to the organisation they are helping. They work vertically through management and laterally across colleagues and client services. Their line manager may allocate capacity while another person sponsors the assignment. Familiarity gives access and contextual knowledge; it can also make assumptions invisible or challenge costly.')+table(['Relationship','What to agree'],[
('Consultant ↔ assignment client','Purpose, work, mutual expectations, participation, and day-to-day decisions.'),
('Consultant ↔ line manager','Capacity, priorities, support, professional boundaries, and escalation.'),
('Line manager ↔ assignment client','Authority to commission, priority conflicts, resource commitments, and how changes are agreed.'),
('Additional sponsor / commissioner','Add a fourth party when the person funding or authorising the work is different from the day-to-day client. Clarify their decision rights rather than merely copying them into emails.')])+p('These are practical contracting maps. The three or four roles may be held by fewer people; affected staff, residents, partners, and other veto holders can still sit outside them. A triangle does not make those people irrelevant.')+ul('Separate your specialist or assurance responsibility from the helping role you are taking.','Make competing commitments visible before you absorb them into unpaid time or hidden compromise.','Agree how information moves between the client and your manager; avoid implied confidentiality that you cannot honour.','Name a route for disagreements that cannot be resolved laterally.','Notice the price of fitting in: what have you stopped asking because ‘that is how we do things here’?')+p('<a href="'+BASE+'downloads/2026-10-01 RedQuadrant internal consulting guide v0.01 BT.pdf">Download the internal consulting guide</a> and <a href="'+BASE+'downloads/2026-10-01 RedQuadrant consulting contract worksheet v0.01 BT.docx">the editable contracting worksheet</a>.')),
s('commercial','From invitation to a workable assignment',p('The earlier commercial consulting material adds the work before a formal contract: earning an invitation, understanding the situation, exploring implications, and agreeing a useful next step. Questions about situation, problem, implication, and value can help. Do not turn them into a technique for manufacturing pain or steering someone towards a preselected purchase.')+p('Separate a genuine need from a request for your preferred service. Discuss the value and constraints of the work, the basis of fees, what is included, and the assumptions behind the estimate. If the client hesitates, ask what the hesitation means. A visible reaction to price may concern budget, fairness, loyalty, authority, or something you have not imagined.')+q('‘I noticed you paused when we discussed the fee. What is on your mind?’')),
s('recontract','Recontract when the agreement stops working',q('‘I was asked to _____. The useful work may be _____. I can take responsibility for _____. I need the client to take responsibility for _____.’')+p('Use this as a preparation prompt, then speak in language that fits the relationship. Describe the change or pattern, explain its effect on the work, ask for the client’s view, and agree a next step. Recontracting may mean continuing with clearer conditions, changing the work, involving another person, or ending.')+p('Internal consultants cannot always leave the organisation. They may still narrow an assignment, refuse an unsupported claim, document a limit, seek a different sponsor, or ask their manager to resolve competing priorities. Be realistic about power and economic dependency; agency exists within constraints.'))
])

page('inquiry','Inquiry, discovery, and a shared picture','Understand enough together to choose useful action, and keep the picture revisable.',[
s('presenting','The presenting issue is a starting point',p('A client asks for a workshop, a restructure, a new system, or a report. Treat the request seriously, then inquire into the work it is meant to do. What prompted it? What has happened before? Who sees the issue differently? What would change if this went well?')+p('‘The problem behind the problem’ and ‘the client behind the client’ are useful prompts. They become unhelpful if they license the consultant to announce the hidden truth. The client may understand political and practical constraints that you do not. Test interpretations together.')+q('‘What makes this the useful thing to do now? What would you want people to do differently afterwards?’')),
s('data','Four kinds of information',table(['Look at','Ask'],[
('The technical or substantive issue','What is happening? What evidence supports that account? What works already?'),
('How others contribute','Which relationships, rules, incentives, and dependencies sustain the situation?'),
('The client’s own contribution','What do you do, or avoid doing, that may help keep this pattern in place?'),
('How the work with you is managed','Does the way we are relating reproduce something important about the wider situation?')])+p('Attend to facts, emotions, and interpretations without conflating them. Compare accounts, observe work where possible, and look for evidence that would challenge your emerging explanation. Inquiry includes strengths, exceptions, aspirations, and possibilities as well as deficits.')),
s('systemic','Make the framing visible',p('A system is a way of organising attention to relationships, purposes, boundaries, and consequences. People can reasonably construct different accounts of the same situation. Ask whose purpose a description serves, what it includes, what it excludes, and what history makes it intelligible.')+p('Distinguish sought purposes, espoused purposes, and purposes suggested by what repeatedly happens. A stated aim of local responsiveness may coexist with approval rules that reward compliance. That is something to investigate, not proof that the stated aim is dishonest.')+p('Move between five worlds when it helps: the citizen or person whose life is affected; the service encounter; the management of operations; leadership and wider direction; and the work of learning and change. An improvement visible in one world may create difficulty in another.')+p('Methods offer particular ways to see. Ask when a method is useful, what it obscures, and what complementary inquiry is needed. The work is to choose and adapt a repertoire, not to impose a complete model on every client.')),
s('joint','Discovery with people',p('Detached research has its place. Consulting discovery also builds the understanding and relationships needed for action. Involve the client in questions, interpretation, and choices. Where third parties hold essential knowledge, make their participation meaningful: explain the purpose, what will happen to their contribution, and what influence they have.')+p('Whole-system discovery broadens who can contribute and see the interdependencies. It does not literally include everyone, abolish hierarchy, or require agreement. Design a defensible boundary, explain it, and leave a route for challenge. Attendance at a workshop does not remove someone’s right to dissent afterwards.')),
s('analysis','Analysis with discipline and humility',p('Earlier consulting teaching includes hypothesis-led analysis, structured questions, evidence, and clear argument. These are useful disciplines. A neat issue tree or a mutually exclusive category set can help organise inquiry, but it may also exclude relationships, history, and conflicting purposes that matter.')+p('Build a shared, revisable picture. Separate observation from interpretation, identify uncertainty, and show what alternative explanations would imply. Do not make a polished presentation carry more certainty than the evidence allows. A ‘single version of the truth’ can silence the differences the client needs to understand.')),
s('feedback','Feedback is an intervention',p('The feedback meeting should enable understanding and choice. Give people a manageable account of what you have found, how you reached it, where the evidence is limited, and what decisions follow. Describe patterns rather than labelling people. Make room for reaction and disagreement before asking for commitment.')+ul('What do people recognise, reject, or need to qualify?','What have we missed, and who should help test it?','What choices are now available, with what consequences?','What will the client do, what will you contribute, and when will both review it?')+p('An evidence report and a meeting for action have different jobs. You may need both. The quality of the work includes whether people can use the findings, not just whether the analysis is technically sound.'))
])

page('conversations','Saying what needs to be said','Authenticity is a practical discipline: describe your experience, test your interpretation, and make a request.',[
s('authenticity','Put your experience into words',p('Authenticity in this work means making relevant experience discussable. It does not require saying everything you feel, performing a supposedly fixed identity, or using emotional disclosure to make the client care for you. Choose language that serves the work and leaves room for an answer.')+q('‘We have postponed our last three review meetings. I am concerned that I am making decisions without your input. Can we agree a review time we can both protect?’')+p('This names an observable pattern, explains its practical effect, and asks for something. Compare it with ‘You are not committed’, which turns an interpretation into a judgement of the person.')),
s('font','Observation, thought, feeling, need, request',p('A participant introduced FONT, drawing on learning with Outlandish and Abi Handley. The letters stand for feelings, observations, needs, and thoughts; Doug Belshaw’s published account works through observation, thought, feeling, and need before a request. The acronym is a memory aid, not a required speaking order.')+table(['Distinction','Example'],[
('Observation','‘We have not had a sponsor review for three weeks.’'),
('Thought / interpretation','‘I am wondering whether this work has become less of a priority.’'),
('Feeling','‘I feel uneasy about proceeding on assumptions.’'),
('Need','‘I need a shared basis for deciding the next stage.’'),
('Request','‘Could we spend twenty minutes deciding whether to continue, change, or pause?’')])+p('Use words you would actually say. Ask ‘What else could this mean?’ before treating your interpretation as settled. A person may be distracted, overcommitted, anxious, or responding to something outside your view. <a href="https://archive.dougbelshaw.com/open-thinkering/font-and-nvc/">Read Doug’s account of FONT and NVC</a>.')),
s('concerns','Listen to concerns before naming a pattern',p('Objections may concern the substance of your proposal, a missing condition, a competing priority, or the personal exposure that change creates. Do not treat disagreement as a symptom called resistance. Answer the question, investigate the concern, and remain open to being wrong.')+p('If objections keep changing after each has been addressed, you may need to discuss the process itself. There is no reliable three-objection rule. Timing depends on the relationship, the stakes, and what you have heard.')+q('‘We have worked through several different concerns, and I sense there is still something unresolved. What would make it difficult to go ahead even if these practical points were addressed?’')+p('Then listen. Naming a pattern is an invitation to inquiry, not a diagnosis that the client must accept.')),
s('power','Power, collusion, and contradictions',p('A sponsor can commission psychological safety while punishing challenge, ask for collaboration while withholding authority, or request an independent recommendation while making clear which answer is acceptable. The consultant can become a buffer, a scapegoat, or a respectable explanation for a decision already made.')+p('Explore what the work can honestly achieve. Ask what the sponsor will do differently and what happens if findings contradict their preference. Consider whether raising a contradiction privately creates more possibility than a public confrontation. Also ask who may pay the price of the choice.')+ul('Name a specific contradiction and its consequences.','Seek a commitment that can be observed, not a general statement of support.','Agree how dissent and unwelcome information will be handled.','Reduce scope or change sponsorship if the required conditions cannot be created.','Use peer support, supervision, and escalation where the consequences exceed your authority.')+p('Economic dependence and unequal power are real. Do not turn ‘be authentic’ into an instruction to ignore them. Work out what can be said, where, with what support, and to what useful end.')),
s('repertoire','Choose your intervention',p('The earlier systemic consulting material explores practical tensions: challenge or work with what is there; surface an issue or let it lie for now; zoom into the encounter or out to the wider pattern; be visible or enable others to act; absorb attention temporarily or return it to those who must own the work.')+p('There is no virtuous pole to select every time. Make a choice, notice its effects, and revise. Working quietly can be skilful; it needs a defensible purpose and a route back to the client’s agency. Becoming the permanent lightning rod can protect others briefly and create dependency over time.')),
s('reflection','Use your own reactions as information',p('A left-hand column exercise separates what was said from what you thought and felt but did not say. Revisit a short difficult exchange. What assumption did you make? What evidence did you have? How did withholding or acting on it affect the next exchange? What could you test openly next time?')+p('The ladder of inference is another useful reminder to distinguish selected observations, meanings, assumptions, and conclusions. Both exercises support inquiry; neither lets you infer another person’s inner state from their behaviour.'))
])

page('intervention','From understanding to action','Every phase affects implementation. Build ownership and capability as you go.',[
s('phases','Five phases, with return journeys',table(['Phase in the Flawless tradition','Practical work'],[
('Entry and contracting','Establish the relationship, purpose, mutual requirements, and a workable agreement.'),
('Discovery and dialogue','Develop information and understanding with the people who will use them.'),
('Analysis and decision to act','Make sense of the findings and choose what to do.'),
('Engagement and implementation','Support participation, action, capability, and review.'),
('Extension, recycling, or termination','Decide what continues, changes, transfers, or ends.')])+p('These phases organise attention; they do not describe a conveyor belt. Discovery can change the contract. Implementation can reveal a different problem. An ending can require another discovery conversation. Participation, ownership, and learning begin at entry.')),
s('participation','Participation with a purpose',p('People need to understand why they are invited, what they can influence, and what is already decided. Do not call a consultation co-design if the important decisions are closed. Where genuine discretion exists, make it visible and give people the information and conditions needed to use it.')+p('Block’s community work offers six useful kinds of conversation: invitation, possibility, ownership, dissent, commitment, and gifts. They direct attention to how people enter, imagine, take responsibility, disagree, choose, and contribute. They are not a compulsory workshop agenda or a way of manufacturing consensus.')+p('Dissent is part of ownership. People may accept responsibility while rejecting a proposal. A commitment is more meaningful when a person can say no.')),
s('design','Design an intervention before choosing an activity',p('Ask what must become possible, for whom, and under what conditions. Then choose the method. A workshop, a series of interviews, a live experiment, a decision meeting, or a change to a routine may each do useful work. An energising event cannot compensate for missing authority or a sponsor who will not act.')+ul('Clarify intent, desired outcomes, and tangible outputs.','Understand the people, their relationships, power, history, and access requirements.','Agree the container: boundaries, participation, confidentiality, decision rights, and ways to disagree.','Prepare inputs and pre-work; test your assumptions about readiness.','Design sequence, timing, environment, and alternatives for predictable difficulties.','Plan reflection, follow-through, ownership, and review before the event.')+p('The facilitation and workshop-design work develops these skills in more detail. '+a('related-practice','See the connections')+' without treating all intervention as a workshop.')),
s('risk','Permission, support, and risk',p('Useful work may require people to take interpersonal or organisational risks. Match challenge with support, permission, and protection appropriate to the setting. A declaration that ‘this is a safe space’ does not remove reporting lines, histories, or the consequences of speaking.')+p('Do not assume depth is always better. A group may need a clear decision process before a deeply personal exchange. Equally, a superficial activity may avoid the contradiction that prevents action. Choose the level of work consciously and within your competence.')+p('A pre-mortem asks people to imagine that the work has failed and explain why. Use it to surface concerns and improve the design. Reducing the discomfort of each immediate interaction can sometimes leave a larger risk unaddressed; test that possibility rather than assuming it is true.')),
s('implementation','Make the next action ownable',p('Connect decisions to an owner, authority, capacity, and a review point. Distinguish an action you can directly deliver from an outcome that depends on many people and conditions. A service or organisation may need changes to routines, information, resources, or management decisions as well as individual skill.')+p('Use short cycles: frame an intention, act, notice what happens, reflect with others, and adjust. Keep evidence about the effects on people who use the service, not just the convenience of the change team. Look for unintended consequences and uneven effects.')+p('Consultants can help people act, but should avoid becoming the load-bearing wall that keeps the whole arrangement standing. Ask what would continue if you stepped away, and what support the organisation would still need.')),
s('ending','End, transfer, or agree new work',ul('Review the original purpose, what happened, and what remains uncertain.','Agree what the client will continue and who holds each responsibility.','Leave usable records, methods, decisions, and access to the work.','Discuss what both parties learned about the relationship.','Name any continuing dependency or risk plainly.','Make an explicit choice: end, extend for a defined purpose, or return to a new contracting conversation.')+p('A satisfied client and a longer engagement are not the only indicators of good work. An informed decision to stop, a useful challenge, or a client who no longer needs you may be a valuable result.'))
])

page('learning','Contracting for learning','Can learning itself be a deliverable? Yes, if the agreement connects inquiry to evidence, decisions, and the ability to act.',[
s('question','The question the September session opened',p('The session distinguished a protected space for co-learning from consultancy commissioned around a predetermined output. It then asked whether learning could itself be a deliverable. The discussion raised the question; it did not settle a contracting or evaluation method. What follows is a proposed development to try in practice.')+p('‘We will learn together’ is too loose on its own. It can conceal an absence of purpose, evidence, or accountability. Yet promising a solution before inquiry begins can be equally misleading. A useful contract makes the inquiry, the client’s participation, and the decisions that learning will inform explicit.')+p('The central test is: what will the client be better able to notice, judge, decide, or do, and what evidence would justify that claim?')),
s('distinctions','Separate four things',table(['Element','What can be agreed','What would count as evidence'],[
('Contracted work and outputs','Questions, participation, access, inquiry activities, records, review meetings, and an agreed decision process.','The work took place to the agreed standard; records show what was examined, including contrary evidence.'),
('Learning','Changes in understanding, assumptions, options, or judgement that matter to the purpose.','People can explain what changed, why, and what difference it makes to a live decision.'),
('Capability and practice','The ability to keep inquiring and acting after the consultant leaves.','A team repeats the review process, tests a new assumption, or changes a routine without consultant prompting.'),
('Wider outcomes','Effects on the service, organisation, or people whose lives are affected.','Appropriate outcome evidence over time, with attention to other influences and unequal effects.')])+p('You can commit to carrying out a disciplined inquiry and producing usable evidence. You can create and agree conditions for learning. You cannot guarantee that people will change their understanding, or that a short assignment will cause a complex public outcome. Agree the ambition and the limits without making the contract empty.')),
s('contract','A practical learning agreement',table(['Agree','Make it concrete'],[
('Purpose and decision','Name the live question and the decision the learning must inform. Who has authority to make it?'),
('Starting account','Record current explanations, evidence, assumptions, disagreements, and known gaps before beginning.'),
('Participation and permission','Identify who must contribute, including people affected. Agree access, time, support, and permission to surface unwelcome information.'),
('Inquiry and evidence','Agree a proportionate mix of observation, existing information, conversations, and bounded tests. Specify what would challenge the starting account.'),
('Responsibilities','Consultant: design, facilitation, analysis, candour, and records. Client: access, participation, decisions, resources, and follow-through. Tailor this split explicitly.'),
('Review points','Put dates in diaries. At each review choose continue, adapt, extend, stop, or transfer. State who can make each choice.'),
('Acceptance','Define what makes the inquiry and its outputs adequate. Do not make acceptance depend on a preferred finding or favourable story.'),
('Resources and boundaries','Set time and cost limits, constraints on tests, information handling, and a process for scope changes.'),
('Transfer','Agree who maintains the learning routine and what evidence will show that it can continue without you.')])+p('A staged agreement can hold purpose and resource limits steady while allowing the method to change. For example, contract first for a bounded discovery phase, then use an explicit decision to commission further work. Avoid an open-ended promise of emergence with no review or stopping rule.')),
s('example','Worked example: a six-week inquiry',p('<strong>Illustrative case, not a reported client engagement.</strong> A public-service team believes repeated hand-offs are delaying help. It wants to decide whether to change a referral rule. Staff disagree about the causes, and people using the service experience the hand-offs differently.')+table(['When','Work and evidence','Decision'],[
('Before the start','Sponsor names the decision owner; team protects time; participants agree how accounts will be used. Record current explanations, a small baseline, and the proposed rule change.','Is there enough access and authority to begin? If not, narrow or pause the work.'),
('Weeks 1–2','Trace a small, explicitly bounded set of journeys with staff and people affected. Compare cases that went well and badly. Record limits of the sample and competing explanations.','At review 1, select a test or decide that more inquiry is needed. Do not imply the sample represents every case.'),
('Weeks 3–4','Try a reversible change within agreed authority and safeguards. Record what happened, including workload shifts, exclusions, and unexpected effects.','At review 2, continue, adjust, or stop the test using the agreed evidence.'),
('Weeks 5–6','Compare the starting account with the evidence. Practise the review process with the team leading it. Prepare a decision record, remaining questions, and ownership for the next cycle.','The authorised client decides whether to adopt, extend, redesign, or reject the proposed rule change.')])+p('The contracted outputs are a shared starting account, an evidence and assumptions record, a bounded test where authorised, two interim reviews, a final decision record, and a transfer exercise. The hoped-for outcome is more useful and timely help. Six weeks cannot by itself establish that outcome or attribute it to the consultant.')+p('A decision not to change the rule can be a successful inquiry if the evidence supports it. Missing access, unsupported conclusions, or a review that never informs a decision are shortcomings to address, not successes to relabel as learning.')),
s('evidence','How would we recognise learning?',table(['Look for','Useful evidence','Insufficient on its own'],[
('A changed explanation','Before-and-after accounts identify an assumption that changed, the evidence, and the implications.','‘We had some good conversations.’'),
('A changed decision','A decision record shows how evidence affected a choice, including a justified no-go.','A report was accepted or a workshop scored highly.'),
('A changed practice','Observe the new routine in use; examine cases where it breaks down or excludes people.','A commitment or an action list.'),
('Retained capability','The client leads another inquiry or review without relying on the consultant.','People attended training or received a toolkit.'),
('A plausible contribution to wider outcomes','Trace the reasoning between action and effect, look for other explanations, and check who benefited.','A favourable indicator treated as proof of causation.')])+p('Agree a small number of useful indicators with the people doing and experiencing the work. Include disconfirming evidence, effort and cost, and consequences for people whose voices are easily missed. Counting ‘lessons learned’ rewards volume; it says little about whether judgement improved.')),
s('wording','Possible wording for a scope of work',q('‘The purpose of this phase is to enable [decision owner] to decide [live question] on a better-evidenced basis. We will jointly examine [questions], test [assumptions], and record evidence, disagreements, and remaining uncertainty. The consultant will provide [contribution]. The client will provide [access, participation, authority, and resources]. At [review dates], we will decide whether to continue, adapt, stop, or agree a further phase. Acceptance concerns the quality and completeness of this agreed work, including evidence that challenges the starting proposal; it does not require a predetermined finding.’')+p('This is practice wording to adapt with the client and the organisation’s contracting requirements. It is not a ready-made legal clause.')),
s('transformative','Where transformative outcomes can help',p('The Transformative Innovation Policy Consortium’s formative evaluation approach connects learning objectives, emerging outcomes, and revisable theories of change. Its setting is innovation policy and systemic transformation. It offers a useful adjacent resource for asking whether experiments are changing the conditions for further change, while addressing timing and attribution difficulties.')+p('My suggestion here is narrower: use a revisable account of how the work might contribute, and review that account against experience. Do not import a transformative-outcomes vocabulary merely to make a small assignment sound ambitious. '+
'<a href="https://tipconsortium.net/tipc-methodology-a-formative-evaluation-theory-of-change-for-transformative-outcomes/">Read TIPC’s methodology</a> and <a href="https://tipconsortium.net/publication/a-formative-approach-to-the-evaluation-of-transformative-innovation-policies/">Molas-Gallart, Boni, Giachi, and Schot’s 2021 paper</a>.')),
s('test','An invitation to test this',p('Take a real brief that asks for a report, workshop, or recommendation. Keep the useful output. Add one learning question, one live decision, one way of testing the starting account, and one review at which changing direction is allowed. Then ask the client what would make that agreement credible.')+p('The unresolved practical question is often power: can the people learning actually change anything? If their answer is no, the contract needs a route to someone who can decide, or a more modest purpose. '+a('related-practice','The five core practices')+' help connect that agreement to the organisation’s everyday conversations, clarity, and learning routines.')+p('<a href="'+BASE+'downloads/2026-10-01 RedQuadrant contracting for learning v0.01 BT.pdf">Download the contracting-for-learning note</a> · <a href="'+BASE+'downloads/2026-10-01 RedQuadrant consulting contract worksheet v0.01 BT.docx">Use the editable worksheet</a>'))
])

page('situations','Practise on the situations you meet','These are constructed practice cases. Use the questions to prepare, then rehearse the conversation.',[
s('workshop','‘We need a workshop’',p('A director asks for a half-day workshop to make a fragmented team collaborate. The director will open the session and leave.')+p('<strong>Inquire:</strong> What can the team decide? What in its tasks, incentives, and management makes collaboration difficult? What will the director contribute after the opening? <strong>Try:</strong> ‘I can help design the session. First, can we agree what people will be able to change and how you will support the decisions?’ <strong>Review:</strong> Did you clarify purpose and authority before selecting activities?')),
s('internal-case','Two clients, one internal consultant',p('Your manager allocates two days a week. The service sponsor assumes you are available whenever needed. You have begun covering the difference.')+p('<strong>Inquire:</strong> Who agreed the priority and capacity? Which work is being displaced? <strong>Try:</strong> ‘We currently have two different assumptions about my availability. Can the three of us agree what can be delivered in the allocated time, and what would need to change?’ <strong>Review:</strong> Did you make the conflict visible without making either party the villain?')),
s('fixed-answer','The recommendation is already chosen',p('A sponsor asks for an independent review, then makes clear that only one recommendation will be acceptable.')+p('<strong>Inquire:</strong> Is the task to investigate, validate evidence, communicate a decision, or implement it? What discretion remains? <strong>Try:</strong> ‘If the decision has been made, we can agree work that supports implementation. If this is an independent review, I need room to reach a different conclusion. Which are you asking for?’ <strong>Review:</strong> Did you establish an honest purpose and avoid promising an independence you cannot deliver?')),
s('access','Repeatedly missing access',p('You are asked to deliver findings but cannot meet the people who do the work. Meetings keep being cancelled.')+p('<strong>Inquire:</strong> What prevents access? Does the sponsor still want this work? What claims would the available evidence support? <strong>Try:</strong> ‘Without those conversations I can give you a limited desk review. I cannot claim it represents how the service operates. Shall we change the access, the scope, or the deadline?’ <strong>Review:</strong> Did you connect your requirement to quality and purpose?')),
s('resistance-case','A new objection at every meeting',p('Every practical concern receives an answer, but the assignment never reaches a decision.')+p('<strong>Inquire:</strong> Is there a substantive gap, an absent decision maker, a risk to someone’s status, or an unwanted proposal? <strong>Try:</strong> ‘There seems to be something we have not yet addressed. What makes this difficult to commit to?’ <strong>Review:</strong> Did you listen before calling the pattern resistance? What changed when you discussed the relationship?')),
s('learning-case','A report that must also build capability',p('The client wants a report by a fixed date and wants the team to learn how to investigate future problems.')+p('<strong>Inquire:</strong> Which inquiry tasks can the team own? What time is protected? Who will lead the next review? <strong>Try:</strong> retain the report, add joint interpretation and a client-led inquiry cycle, and agree evidence of learning. <strong>Review:</strong> Did the contract resource both aims, or simply add ‘capability building’ to the promise?')),
s('speed','‘AI means we should deliver faster’',p('A team can generate analyses and documents quickly, while its sponsor presses for shorter delivery times. It is unclear whether understanding and decisions are improving.')+p('<strong>Inquire:</strong> Which part of the work is actually faster? What still needs human inquiry, verification, consent, and judgement? Who checks errors and consequences? <strong>Try:</strong> ‘We can reduce drafting time. Let us agree how that changes cost or scope, and what evidence and client decisions still require time.’ <strong>Review:</strong> Did you distinguish faster production from useful learning and responsible action? This is a consulting scenario, not an assessment of any particular AI tool.')),
s('absence','The principal client is absent',p('The person who asked for the work cannot attend. A colleague is present but is unsure what they can decide.')+p('<strong>Inquire:</strong> What authority has been delegated? What can usefully happen today? Which decisions need the principal? <strong>Try:</strong> ‘We can explore the situation and prepare options. Before committing to a scope, can we confirm who has authority and arrange a decision conversation?’ <strong>Review:</strong> Did you use the time without inventing an agreement?')),
s('rehearse','A 25-minute practice round',ul('<strong>3 minutes:</strong> choose a real moment, define the purpose of the conversation, and explain only the context needed.','<strong>6 minutes:</strong> practise with a colleague playing the client and another observing. The observer notes actual words, questions, assumptions, and shifts in responsibility.','<strong>5 minutes:</strong> hear the client’s experience, then the observer’s evidence. Avoid a flood of advice.','<strong>6 minutes:</strong> replay the difficult moment with one deliberate change.','<strong>5 minutes:</strong> reflect and choose one action to try in practice.')+p('If practising alone, write both sides of the exchange, including the response you least want to hear. Ask what that response would make you change. The triad rehearsal was part of the wider teaching repertoire; it was not completed in the September online session.')),
s('next','A short reflection after real work',ul('What was I trying to make possible?','What did I observe, and what did I infer?','Where did I take over, withdraw, or conceal a requirement?','What did the client contribute or decide?','What did the intervention change, including unintended effects?','What will I repeat, alter, or test next time?'))
])

page('related-practice','Connections to the wider practice','Systemic consulting has a distinct focus. These adjoining disciplines help turn a consulting agreement into effective work.',[
s('boundaries','Keep the distinctions useful',table(['Body of practice','Its particular question','Connection to consulting'],[
('Systemic consulting','How can I help within this relationship and wider situation?','Role, contract, inquiry, responsibility, power, and ownership.'),
('Facilitation','How can people work together on what matters?','Design and hold a process that enables participation, disagreement, decisions, and learning.'),
('Workshop design','What sequence and conditions will enable the intended work?','Translate purpose into preparation, participation, environment, activities, outputs, and follow-through.'),
('Four dynamics','Which forms of differentiation and connection does this situation need?','Notice what is being overused, neglected, or kept apart in the group or organisation.'),
('Five core practices','What everyday practices make purposeful adaptation possible?','Connect an assignment to conversations, clarity, learning, culture, and intent.'),
('Intervention and OD skills','How can people change patterns of organising and sustain the change?','Combine inquiry, relationships, process, structures, action, reflection, and capability over time.')])+p('The same piece of work can draw on all of these. They are connected practices with different questions, not interchangeable names for one model. This guide concentrates on consulting; the links below lead into the adjoining work.')),
s('facilitation','Facilitation and workshop design',p('Facilitation begins before people enter the room and continues after they leave. The consulting contract clarifies the purpose, sponsorship, authority, and relationship. Process design then asks who needs to work together, what information they need, how they will participate, and how the work will be used.')+p('The design canvas used in the wider material considers people, preparation and inputs, environment, pitfalls and assumptions, intent, the container, outcomes, outputs, agenda, and reflection. Use it to test the design rather than fill boxes mechanically. Support and challenge, permission and protection, and the facilitator’s own authority all deserve attention.')+p('<a href="/library/facilitation-and-systems-consulting/">Facilitation and systems consulting materials</a> · <a href="/library/large-group-processes/">Large-group processes</a> · <a href="https://antlerboy.github.io/largegroupprocess/">Search and compare participatory methods</a>')),
s('four','Four dynamics',p('My four-dynamics account develops connections with Oshry’s work on differentiation, homogenisation, individuation, and integration. The practical language is segment, blend, empower, and harmonise. Each enables something that the others alone cannot provide.')+table(['Dynamic','What it enables','Consulting question'],[
('Segment','Specialised groups develop distinctive knowledge, experience, and capability.','Where do differences need space to develop and be heard?'),
('Blend','People share knowledge and experience across boundaries and develop commonality.','Who needs to learn from whom, and where are experiences kept apart?'),
('Empower','Individuals develop and use their own talents, judgement, and agency.','What can each person decide or contribute without waiting for permission?'),
('Harmonise','People align around shared purpose and coordinate their contributions.','What agreements connect the different contributions into useful action?')])+p('These are continuing dynamics, not personality types or stages to complete. A workshop may blend experience while the organisation still prevents empowerment. A common purpose can help harmonise without erasing the differences that make the work intelligent. Ask what combination is needed here.')+p('<a href="/library/four-dynamics/">Four dynamics collection</a> · <a href="/library/files/talks/introduction-to-four-dynamics.pdf">Introduction</a> · <a href="/library/files/talks/positive-dynamics-differentiation-and-integration.pdf">Developed account</a>')),
s('five','Five core practices',table(['Practice','Meaning in this work'],[
('Productive conversations','Tell the truth, surface disagreement, test reasoning, and make commitments people understand.'),
('Clarity practices','Keep purpose, priorities, roles, decision rights, ownership, and scope sufficiently clear to act.'),
('Learning as practice','Try, notice, reflect, adjust, and repeat as part of the work.'),
('Culture shaping','Attend to repeated experiences: behaviour, systems and structures, and the symbols and stories that make expectations credible.'),
('Good and clear intent','Connect action to value for people and communities; make purposes and trade-offs clear enough for responsible judgement.')])+p('The first three form a learning system: conversations make experience discussable, clarity makes action and responsibility possible, and learning changes what happens next. Culture shaping attends to what repeated experience teaches people. Good and clear intent gives the work direction without trying to specify every action.')+p('For a learning contract, ask whether these practices will exist after the assignment. Who convenes the conversation? What is clear enough to decide? How does the next cycle happen? What organisational signals support or contradict it? Whose interests does the intent serve?')+p('<a href="/library/five-core-practices/">Five core practices collection</a> · <a href="/library/files/talks/clarity-practices.pdf">Clarity practices teaching deck</a> · <a href="/library/productive-conversations/">Productive conversations</a>')),
s('od','Intervention, OD, and systems practice',p('The wider intervention material adds ways to examine service demand and flow, operating arrangements, leadership, culture, boundaries, and the capacity to adapt. Technical changes and adaptive work may both be needed. A new process can fail because its conditions of use have not changed; a conversation can be useful without being sufficient.')+p('Select methods against the situation and your competence. Different approaches illuminate different relationships. Avoid a toolbox display that asks the client to admire your range. Explain what a method helps people do, what it requires, and how you will know whether it is helping.')+p('<a href="/library/systems-leadership-change-practice/">Systems leadership and change</a> · <a href="/library/viable-system-model/">Viable System Model</a> · <a href="https://transduction.systems/systems-thinking/practice/">Systems thinking practice tools</a>')),
s('relational','Relational and place-based public services',p('This is a related field of application. The consulting question is how we help; the public-service question includes how relationships, judgement, organisational arrangements, and place make useful service possible. Keep attention on the people whose lives are affected, not only the commissioning organisation.')+p('<a href="/library/relational-public-services/">Relational public services collection</a> · <a href="/sysprac26/">SysPrac26 follow-up sessions</a>'))
])

page('september-session','The 30 September 2026 conversation','A thematic account of the slide-free systemic consulting session, including the discussion, chat resources, and unfinished questions.',[
s('opening','Different starting points',p('Participants brought internal and external consulting, public-service work, education, technology, and organisational change. The opening question was practical: how do we help without defaulting either to expert answers or unquestioning delivery of a brief? The discussion drew on varied experiences rather than working through a slide deck.')+p('Joining and audio difficulties, organisational device restrictions, and limited use of breakouts affected the session. These are reminders that the conditions for participation are part of design. The account below follows themes rather than reproducing every exchange.')),
s('roles-session','Expert, pair of hands, collaborator, and the quiet fourth role',p('The opening role exercise distinguished telling the client what to do, doing what the client asks, and working collaboratively. Several people recognised a fourth position: doing useful work quietly within a constrained brief. That opened questions about tact, transparency, agency, and whether indirect work can become manipulation.')+p('A Steve Jobs clip raised a challenge about consultants’ accountability for advice. The discussion considered staying to help deliver and taking a more direct leadership role. The useful distinction was whether responsibility and authority had been made explicit. '+a('roles','Read the roles chapter')+'.')),
s('service-session','The pressures in the consulting relationship',p('The consultant’s wish to be accepted and useful can prompt premature expertise or compliance. The client brings their own knowledge, uncertainty, and exposure. Oshry’s space of service helped describe these pressures without reducing them to personality.')+p('Mutual responsibility and co-learning offered an alternative. The 50/50 and 100/100 language was about participation in the relationship, rather than equal tasks or formal authority. Internal consulting made the additional relationships with managers and sponsors especially visible.')),
s('contract-session','Contracting keeps happening',p('The group discussed contracting as an explicit agreement about the relationship as well as the task, including wants, offers, access, and what happens when things become difficult. A relationship ‘prenup’ was one memorable description. Internal work may need a triangular or rectangular agreement between the consultant, client, line manager, and a separate sponsor.')+p('A practical veto question was: ‘If we both agree this is the right thing to do, who can still say no?’ Recontracting becomes necessary when the useful work differs from the initial request or the agreed conditions are unavailable. '+a('contracting','Read the contracting chapter')+'.')),
s('inquiry-session','Inquire before solving',p('The client behind the client and the problem behind the problem prompted exploration of wider relationships and purposes. The discussion also challenged a consultant’s temptation to claim superior knowledge of the ‘real’ problem. Political context, the client’s own judgement, and the management of the issue all matter.')+p('An anonymised example showed that holding a justified professional position can leave space for more useful work later. Other examples explored how a consultant can be recruited into existing tensions or asked to carry responsibility that belongs elsewhere. '+a('inquiry','Read the inquiry chapter')+'.')),
s('power-session','Authenticity, access, and power',p('Examples concerned unavailable sponsors, distracted senior leaders, contradictory expectations, and the difficulty of challenging powerful people. The central move was to describe an experience or pattern and its effect on the work, then make a request. Authenticity was discussed as putting relevant experience into words, not saying every thought or emotion.')+p('The conversation recognised economic dependence, limited exit for internal consultants, and the risks of scapegoating or collusion. Agency cannot simply be demanded from a person whose choices are constrained. Support, timing, scope, and escalation all affect what is possible.')),
s('font-session','FONT, interpretation, and concerns',p('The chat introduced FONT and Nonviolent Communication, separating observation, thought, feeling, and need before a request. Another contribution asked what meaning we had placed on an event and what else it might mean. Both helped distinguish an observation from a story about someone’s intention.')+p('Repeated objections led to discussion of when to name the pattern itself. The first task remains to understand and respond to the concern. A later pricing example showed how an unexpected reaction can have an explanation the consultant has not considered, including loyalty to an existing relationship. '+a('conversations','Read the conversations chapter')+'.')),
s('learning-session','Outputs, outcomes, and learning',p('The group distinguished producing a report from helping create an outcome, while recognising that a report may have an honest and necessary purpose. Sometimes the first useful achievement is understanding. The conversation also touched on organisational performance that looks like progress without changing much.')+p('A question about protected co-learning asked whether learning itself could be contracted as a deliverable, especially when a commission expects predetermined outputs. Transformative outcomes were mentioned, but no evaluation method was agreed. '+a('learning','The new contracting-for-learning chapter')+' develops that open question into a proposed agreement, example, and evidence framework.')),
s('risk-session','Risk, accountability, and the unsaid',p('A pre-mortem was suggested as a way to reveal risks before the work proceeds. One hypothesis was that repeatedly avoiding small interpersonal risks can leave a larger project risk unaddressed. This was an idea to examine, not a conclusion demonstrated by the session.')+p('A participant’s ‘three Ds’ — disadvantage, dysfunction, and demise — offered another prompt for considering consequences. A Dear John comedy clip illustrated the social conventions around naming an uncomfortable shared experience. The clips and heuristics were discussion prompts, not evidence for a general law.')),
s('closing','What the session left us with',ul('A wish for a visual organiser and a map connecting problems with possible responses.','A request for the internal consulting and triangular contracting material.','An unresolved question about contracting for learning.','A practical recontracting sentence to use on a live assignment.','A need for rehearsal and replay: the planned triad practice was not completed in this online session.','A reminder that ‘flawless’ concerns conscious choice in the relationship, rather than perfection.')+p('This guide supplies the visual organiser, a practice map, the internal consulting note, worked situations, and the developed learning material. '+a('resources','The resource directory')+' retains the chat links and earlier reading routes.')),
s('account','About this account',p('The account synthesises the session transcript, Teams chat, facilitator notes, and earlier teaching material. Participant examples have been generalised and anonymised. The raw transcript and recording are not published here; the session closed with an explicit statement that the transcript was not intended for circulation. Publicly authored resources retain their attribution.')+p('This is a learning resource, not verbatim minutes or a claim that the group endorsed every subsequent development. Corrections and alternative interpretations are welcome.'))
])

RESOURCES = [
('Start here',[
('Peter Block: Flawless Consulting','https://designedlearning.com/helpful-checklists-and-worksheets/','Designed Learning’s checklists and worksheets for responsibility, contracting, discovery, meetings for action, and implementation. Read alongside the book; the publisher’s material has its own terms.'),
('Thriving in the space of service','https://chosen-path.org/2022/01/26/thriving-in-the-space-of-service-for-consultants-coaches-facilitators-business-partners/','My account of the pressures on consultants, coaches, facilitators, and business partners.'),
('Peter Block on relationships, resistance, and Flawless Consulting','https://www.buzzsprout.com/2073535/episodes/19669919-peter-block-relationships-resistance-and-the-relevance-of-flawless-consulting','The specific Messy Social Work episode discussed in September.'),
('Systemic consulting: rethinking the consultant’s role','https://www.systemspractice.org/resources/systemic-consulting-rethinking-consultants-role-workshop-sysprac25','Public SysPrac25 resource: partnership, dialogue, co-creation, and a systemic consulting repertoire.'),
('Systems consulting and facilitation, STSP26','https://www.dropbox.com/scl/fi/ca3lalnnjdkt06rx39nm6/2026-03-24-STSP26-systems-conulting-and-facilitation-Benjamin-P-Taylor.pdf?rlkey=u5txcu880d7ht4ceu8ognmu7z&dl=0','March 2026 presentation connecting consulting, facilitation, humanism, agency, and intervention design.')]),
('All the September chat links',[
('Tradecraft','https://www.tradecraft.is','Doug Belshaw’s recommendation on building an advisory practice.'),
('Nonviolent Communication overview','https://en.wikipedia.org/wiki/Nonviolent_Communication','The introductory reference shared in chat; a general overview rather than the specific FONT account.'),
('FONT and NVC','https://archive.dougbelshaw.com/open-thinkering/font-and-nvc/','Doug Belshaw’s account of learning with Outlandish and Abi Handley. Distinguishes observation, thought, feeling, need, and request.'),
('We Are Open pre-mortem, archived','https://web.archive.org/web/20250211083310/https://learnwith.weareopen.coop/pre-mortem/','The archived resource supplied in chat. Archive availability can vary.'),
('Breaking the Shell','https://www.breakingtheshell.com/','My pre-mortem approach to surfacing what could prevent useful work.'),
('Dear John clip','https://www.youtube.com/watch?v=ryQ2bH1kGBk','Comedy illustration about naming an uncomfortable shared convention. Included as a discussion prompt.'),
('Steve Jobs on consulting','https://youtu.be/-c4CNB80SRc','The clip offered as a challenge about accountability and the consequences of advice.'),
('Messy Social Work: Apple Podcasts','https://podcasts.apple.com/gb/podcast/messy-social-work/id1651861448','Programme listing shared in chat.'),
('Messy Social Work: choose a platform','https://pod.link/1651861448','Platform-neutral route to the programme.'),
('Messy Social Work: programme home','https://www.buzzsprout.com/2073535','The programme archive. The specific Peter Block episode is linked above.'),
('A Necessary Tangle','https://transduction.systems/','Systems resources and connected writing.'),
('Systems thinking practice tools','https://transduction.systems/systems-thinking/practice/','The direct practice route shared during the discussion.'),
('Raven','https://raven.evermind.ai/','An adjacent AI resource shared by a participant. Inclusion records the conversation; it is not a performance evaluation or recommendation.'),
('VSM toolkit project','https://framagit.org/dajbelshaw/vsmkit/','Doug Belshaw’s developing project, shared in chat. Treat it as a project to explore, not a validated consulting method.')]),
('Earlier reading and listening',[
('My favourite Peter Block quotes','https://chosen-path.org/2021/02/15/my-favourite-peter-block-quotes/','Provocations from Block’s work, gathered with context.'),
('Peter Block on contracting','https://www.forbes.com/sites/rodgerdeanduncan/2020/01/28/peter-block-on-the-key-to-contracting-with-your-client/','Rodger Dean Duncan’s interview from the teaching reading list.'),
('Peter Block on relationships','https://www.forbes.com/sites/rodgerdeanduncan/2020/01/21/peter-block-on-why-relationships-are-paramount/','The companion interview.'),
('Dirty or clean consulting','https://www.linkedin.com/pulse/do-you-want-dirty-clean-consulting-dr-richard-claydon/','Richard Claydon’s contrasting perspective on consulting practice.'),
('Peter Block on The Amiel Show','https://amielhandelsman.com/amiel-show-041-peter-block/','Earlier listening on Block’s work.'),
('Ed Schein on The Amiel Show','https://amielhandelsman.com/amiel-show-049-ed-schein/','Helping and relationship as an adjacent perspective.'),
('Techniques to Match Our Values','http://www.marvinweisbord.com/wp-content/uploads/2010/04/Techniques%20to%20Match%20Values.pdf','Marvin Weisbord on alignment between values and practice; historical external PDF.'),
('Requiem for Bethlehem','http://www.marvinweisbord.com/wp-content/uploads/2010/04/Requiem%20for%20Bethlehem.pdf','Weisbord on learning and organisational outcomes; historical external PDF.'),
('Let People Be Responsible','http://www.marvinweisbord.com/wp-content/uploads/2010/04/Consulting-Today-Weisbord-Janoff-2008.pdf','Weisbord and Sandra Janoff on participation and responsibility; historical external PDF.'),
('The Peter Block community exercise','https://www.dropbox.com/scl/fi/pd58brghxfzi7hmcjpq5e/The-Peter-Block-community-exercise.pdf?rlkey=effn2ww7mw5jak96bg43zazga&dl=0','A practical route into participation and community.'),
('Dare to Un-Lead','https://www.youtube.com/watch?v=3f1BcaiPe-4','Céline Schillinger resource from the March teaching materials.'),
('Formative evaluation and transformative outcomes','https://tipconsortium.net/tipc-methodology-a-formative-evaluation-theory-of-change-for-transformative-outcomes/','TIPC’s methodology. Added to develop the learning question; it was not a method taught in September.')])]
VIDEO_IDS = [('Flawless Consulting introduction','bKipHuq8hUU'),('Contracting','MKieKRN59Y8'),('Authenticity and vulnerability','4YZ85NJef_Q'),('Following the steps','Rsy6Qfa-tPM'),('It is all implementation','0HsekFRQNSY'),('Touchy feely crap','UHzb5sUgXqk'),('Feedback','f7V6NhhmB-U'),('Project managers','s2qQUBsR1GM'),('The book is just a book','v83AZYyVP0w'),('Are you the problem?','IDirRkbyEP0'),('Aliveness','V5FAP_JXihQ'),('Am I too pushy?','sz4ckRfzQak'),('Presenting problems','3B1CXWplqy4'),('I am here to fix you','62C6C0VXkVY'),('Changing a hostile work environment','E4bPvQWEKVs'),('Peter Block interview','XMjxPNSBZ7A')]
resource_sections = [s('downloads','Downloads',p('The practice map is designed to travel with a short email. The internal consulting guide and editable worksheet support a real contracting conversation. The learning note develops the September question.')+'<ul class="downloads">'+''.join('<li><a download href="'+BASE+'downloads/'+e(name)+'">'+e(label)+'</a> <span>'+kind+'</span></li>' for name,label,kind in [
('2026-10-01 RedQuadrant systemic consulting practice map v0.01 BT.png','Practice map','PNG · one image'),
('2026-10-01 RedQuadrant systemic consulting practice map v0.01 BT.pdf','Practice map for printing','PDF · one page'),
('2026-10-01 RedQuadrant internal consulting guide v0.01 BT.pdf','Internal consulting and triangular contracting','PDF'),
('2026-10-01 RedQuadrant consulting contract worksheet v0.01 BT.docx','Consulting contract worksheet','Word · editable'),
('2026-10-01 RedQuadrant contracting for learning v0.01 BT.pdf','Contracting for learning','PDF')])+'</ul>')]
for idx,(title,items) in enumerate(RESOURCES):
    resource_sections.append(s('links-'+str(idx), title, '<ul class="resources">'+''.join('<li><h3><a href="'+e(url)+'">'+e(title)+'</a></h3>'+p(desc)+'</li>' for title,url,desc in items)+'</ul>'))
resource_sections += [s('videos','Peter Block video shelf',p('The short videos below recur in the earlier learner guides. They are retained as a reading route, with the original platform responsible for availability. Video labels come from the teaching resource list; they are not transcripts.')+ul(*['<a href="https://www.youtube.com/watch?v='+vid+'">'+e(title)+'</a>' for title,vid in VIDEO_IDS])),
s('lineage','How the earlier material is incorporated',table(['Source family','Concepts carried into this guide'],[
('2022 Flawless summary and planning; 2023 interventions teaching','Roles, assumptions, responsibility, five phases, contracting, discovery, feedback, engagement, and endings.'),
('2022 commercial and core consulting programmes','Earning an invitation, scoping, client need and value, questioning, analytical discipline, clear argument, implementation, and reflective practice.'),
('SysPrac25; October 2025 learner guides; 2025 reflection and workbook material','Systemic framing, plural purposes, boundaries, power, history, five worlds, practical tensions, joint discovery, participation, and reflective exercises.'),
('March 2026 systems consulting, facilitation, and intervention sessions','Humanism and agency, internal consulting, vertical and lateral relationships, self-management, permission and protection, design, and capability.'),
('30 September 2026 transcript, chat, and facilitator notes','The lived consulting relationship, ongoing contracting, authenticity, access, power, concerns, learning, and the linked resources.'),
('Related four-dynamics and five-core-practices material','Connections to group and organisational dynamics, conversations, clarity, learning routines, culture, and intent.')])+p('This coverage is a synthesis of the materials available for this edition. Earlier decks overlap and use different language; their ideas are consolidated rather than repeated. Public versions are linked where available. Private client material, participant details, and the September raw transcript are not republished.')),
s('credit','Attribution and use',p('Benjamin P Taylor’s synthesis and practice prompts draw on Peter Block, Barry Oshry, and the other authors named alongside their work. FONT is attributed through Doug Belshaw’s account of Outlandish and Abi Handley. The five core practices and four dynamics are connected accounts in my own teaching, with their wider influences explained in the source collections.')+p('This guide is not an accredited Flawless Consulting course and does not replace the original books or licensed materials. Linked sources retain their own authorship and terms. You are welcome to share links to this guide and the downloadable practice notes with attribution. External links may move or require an account; inclusion is not an endorsement of every claim.'))]
page('resources','Resources and downloads','The chat links, earlier teaching routes, practical notes, and the sources behind the guide.',resource_sections)

def plain(html): return re.sub(r'\s+', ' ', re.sub('<[^>]+>', ' ', html)).strip()
def render():
    ROOT.mkdir(exist_ok=True)
    index=[]
    for n,pg in enumerate(PAGES):
        slug=pg['slug']; url=BASE+(slug+'/' if slug else '')
        nav=''.join('<a '+('aria-current="page" ' if x['slug']==slug else '')+'href="'+BASE+(x['slug']+'/' if x['slug'] else '')+'">'+e(x['title'] if not x['slug'] else {'roles':'Roles','contracting':'Contracting','inquiry':'Inquiry','conversations':'Conversations','intervention':'Intervention','learning':'Learning','situations':'Practice','related-practice':'Connections','september-session':'September session','resources':'Resources'}[x['slug']])+'</a>' for x in PAGES)
        toc='<nav class="toc" aria-label="On this page"><p>On this page</p>'+''.join('<a href="#'+sec['id']+'">'+e(sec['title'])+'</a>' for sec in pg['sections'])+'</nav>'
        body=''.join('<section class="chapter-section" id="'+sec['id']+'"><h2>'+e(sec['title'])+'</h2>'+sec['body']+'</section>' for sec in pg['sections'])
        for sec in pg['sections']: index.append(dict(title=sec['title'],chapter=pg['title'],url=url+'#'+sec['id'],text=plain(sec['body'])))
        nextpg=PAGES[(n+1)%len(PAGES)]
        html='''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'''+f'<title>{e(pg["title"])} | Systemic consulting | Benjamin P Taylor</title><meta name="description" content="{e(pg["deck"])}"><link rel="canonical" href="https://antlerboy.com{url}"><meta property="og:title" content="{e(pg["title"])}"><meta property="og:description" content="{e(pg["deck"])}"><meta property="og:image" content="https://antlerboy.com{BASE}practice-map.png"><link rel="stylesheet" href="{BASE}style.css"><script defer src="{BASE}guide.js"></script>'+'''</head><body><a class="skip" href="#main">Skip to content</a><header><div class="mast"><a href="/" class="brand">Benjamin P Taylor <span>antlerboy</span></a><a href="/library/">Public work library ↗</a></div>'''+f'<nav class="chapters" aria-label="Guide chapters">{nav}</nav></header><main id="main"><div class="hero"><p class="eyebrow">A field guide · 2022–2026</p><h1>{e(pg["title"])}</h1><p class="deck">{e(pg["deck"])}</p><p class="edition">Benjamin P Taylor · First edition, 1 October 2026</p></div><div class="reading-layout">{toc}<article>{body}<nav class="next" aria-label="Next chapter"><span>Continue</span><a href="{BASE}{nextpg["slug"]+("/" if nextpg["slug"] else "")}">{e(nextpg["title"])} →</a></nav></article></div></main><footer><p>Systemic consulting · Benjamin P Taylor</p><p><a href="{BASE}resources/#lineage">Sources and scope</a> · <a href="https://github.com/antlerboy/aboutme/issues/1">Suggest a correction</a> · <a href="mailto:benjamin.taylor@redquadrant.com">Get in touch</a></p><p>Purpose, relationship, action, and learning. Keep the work ownable.</p></footer></body></html>'
        dest=ROOT/slug/'index.html'; dest.parent.mkdir(parents=True,exist_ok=True); dest.write_text(html)
    (ROOT/'search.json').write_text(json.dumps(index,ensure_ascii=False,indent=2))
    print(f'Built {len(PAGES)} pages, {len(index)} searchable sections, '+str(sum(len(plain(x['body']).split()) for pg in PAGES for x in pg['sections']))+' words.')
if __name__=='__main__': render()
